### ISSUE TITLE
inconsistent indentation with tabs and spaces

### ISSUE THREAD

**Issue by ebirn** [CostaLab/reg-gen#104]
Python 3.6 complains about mixed indendation here (tabs and spaces):

https://github.com/CostaLab/reg-gen/blob/d3086bd94779c00e5446f460a0cd32b2c79e1b75/rgt/filterVCF/filterVCF.py#L74

```
Traceback (most recent call last):
  File "/software/RGT/0.11.7-foss-2018b-Python-3.6.6/bin/rgt-filterVCF", line 11, in <module>
    load_entry_point('RGT==0.11.7', 'console_scripts', 'rgt-filterVCF')()
  File "/software/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/software/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/software/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/software/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/software/RGT/0.11.7-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/rgt/filterVCF/filterVCF.py", line 73
    s = sum(map(lambda x: x[0], density_seq[coord[0]:coord[1]]))
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation```

Best,
Erich

**Comment by fabio-t** [comment]
This is a specific fix within a larger issue, see https://github.com/CostaLab/reg-gen/issues/12

closing this for now
