### ISSUE TITLE
rgt-hint   ERROR:root:get raw signal failed

### ISSUE THREAD

**Issue by crazyhottommy** [CostaLab/reg-gen#112]
Hi,

congrats for the HINT paper on ATAC.

I was following https://www.regulatory-genomics.org/hint/tutorial/

```
rgt-hint --version
HINT - Regulatory Analysis Toolbox (RGT) - v0.11.8
time rgt-hint differential --organism=hg19 --nc 10 --mpbs-file1=./match/pbmc_cluster_10_footprint_mpbs.bed --mpbs-file2=./match/pbmc_cluster_2_footprint_mpbs.bed --reads-file1=out-cluster-10.bam --reads-file2=out-cluster-2.bam --condition1=cluster10 --condition2=cluster2 --output-location=cluster10_vs_cluster2
ERROR:root:get raw signal failed
Traceback (most recent call last):
  File "/n/home02/mtang/.local/lib/python2.7/site-packages/rgt/HINT/DifferentialAnalysis.py", line 264, in diff_analysis_run
    res = pool.map(get_raw_signal, mpbs_list)
  File "/n/home02/mtang/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/n/home02/mtang/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/n/home02/mtang/.local/bin/rgt-hint", line 11, in <module>
    sys.exit(main())
  File "/n/home02/mtang/.local/lib/python2.7/site-packages/rgt/HINT/Main.py", line 89, in main
    args.func(args)
  File "/n/home02/mtang/.local/lib/python2.7/site-packages/rgt/HINT/DifferentialAnalysis.py", line 269, in diff_analysis_run
    signal_dict_by_tf_1[mpbs_name] = res[idx][0]
UnboundLocalError: local variable 'res' referenced before assignment

real    1m4.915s
user    4m2.373s
sys     0m42.495s
```

Thank you!
Ming

**Comment by lzj1769** [comment]
Hi Ming,

It seems that you asked more cores than your machine actually has. 
can you try to set --nc to a small number, say 4 and run the command again.

Best,
Li

**Comment by crazyhottommy** [comment]
Hi,
I set it to 1 and still same error

``
time rgt-hint differential --organism=hg19 --bc --nc 1 --mpbs-file1=./match/pbmc_cluster_10_footprint_mpbs.bed --mpbs-file2=./match/pbmc_cluster_2_footprint_mpbs.bed --reads-file1=out-cluster-10.bam --reads-file2=out-cluster-2.bam --condition1=cluster10 --condition2=cluster2 --output-location=cluster10_vs_cluster2
ERROR:root:get bias corrected signal failed
Traceback (most recent call last):
  File "/n/home02/mtang/.local/lib/python2.7/site-packages/rgt/HINT/DifferentialAnalysis.py", line 253, in diff_analysis_run
    res = pool.map(get_bc_signal, mpbs_list)
  File "/n/home02/mtang/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/n/home02/mtang/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/n/home02/mtang/.local/bin/rgt-hint", line 11, in <module>
    sys.exit(main())
  File "/n/home02/mtang/.local/lib/python2.7/site-packages/rgt/HINT/Main.py", line 89, in main
    args.func(args)
  File "/n/home02/mtang/.local/lib/python2.7/site-packages/rgt/HINT/DifferentialAnalysis.py", line 269, in diff_analysis_run
    signal_dict_by_tf_1[mpbs_name] = res[idx][0]
UnboundLocalError: local variable 'res' referenced before assignment

real    2m35.392s
user    0m59.285s
sys     0m11.080s
```

**Comment by crazyhottommy** [comment]
problems with the bam files?

**Comment by lzj1769** [comment]
Can you share your BAM files with us, if possible?
also the motif matching results: pbmc_cluster_10_footprint_mpbs.bed, pbmc_cluster_2_footprint_mpbs.bed

so I can figure out why.

Best,
Li

**Comment by crazyhottommy** [comment]
please download here https://drive.google.com/open?id=1d1UXNKhGWwinuInGJsUzUAEHC01qGMmT

**Comment by lzj1769** [comment]
Hi,

The reason why rgt-hint fails is there are some unmapped reads in the BAM file, which usually should be removed before we perform the differential analysis.  
This problem is fixed in the develop branch by filtering the unmapped reads out first.
If you want to use it now, please install RGT as follows:
```
git clone https://github.com/CostaLab/reg-gen.git
cd reg-gen
git checkout develop
python setup.py install --user
```

Best,
Li

**Comment by crazyhottommy** [comment]
Thanks Li ! If I do not want to install the development version, can  I do samtools view -F 4 for my bam first and it should work with the old version?

**Comment by lzj1769** [comment]
> Thanks Li ! If I do not want to install the development version, can I do samtools view -F 4 for my bam first and it should work with the old version?

Yes, I think so.
For me, I usually remove the reads with bad map quality, like 30, with below command:
`samtools view -bq 30 old.bam > filter.bam`
