### ISSUE TITLE
urllib2.URLError problem

### ISSUE THREAD

**Issue by hugch2010** [CostaLab/reg-gen#119]
Hi, 
During my test, I encountered an error as follows:
rgt-hint differential --organism=mm9 --bc --nc 6 --mpbs-file1=./match/cDC1_mpbs.bed --mpbs-file2=./match/pDC_mpbs.bed --reads-file1=cDC1.bam --reads-file2=pDC.bam --condition1=cDC1 --condition2=pDC --output-location=cDC1_pDC
Traceback (most recent call last):
  File ".../rgt-hint", line 10, in <module>
    sys.exit(main())
  File ".../python2.7/site-packages/rgt/HINT/Main.py", line 90, in main
    args.func(args)
  File ".../python2.7/site-packages/rgt/HINT/DifferentialAnalysis.py", line 311, in diff_analysis_run
    pool.map(line_plot, plots_list)
  File ".../python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File ".../python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

My rgt version is v0.12.1. Please help me. Thank you.

**Comment by lzj1769** [comment]
Hi, @hugch2010 

It seems there is something wrong with your internet connection.
You can run below python codes to check it?
```
import urllib2
url = urllib2.urlopen("http://weblogo.threeplusone.com/create.cgi")
```

Best,
Li

**Comment by hugch2010** [comment]
Appreciate your help, I tested at a node with internet connection and succeed, thanks.
