### ISSUE TITLE
Error when calling differential peaks

### ISSUE THREAD

**Issue by re2srm** [CostaLab/reg-gen#122]
Hello, when running THOR to call differential peaks, I am getting the following error:

Traceback (most recent call last):
  File "/scratch/software/bin/rgt-THOR", line 6, in <module>
    from rgt.THOR.THOR import main
  File "/scratch/software/lib/python3.6/site-packages/rgt/THOR/THOR.py", line 30, in <module>
    from .dpc_help import get_peaks, _fit_mean_var_distr, initialize, merge_output, handle_input
  File "/scratch/software/lib/python3.6/site-packages/rgt/THOR/dpc_help.py", line 28, in <module>
    from .MultiCoverageSet import MultiCoverageSet
  File "/scratch/software/lib/python3.6/site-packages/rgt/THOR/MultiCoverageSet.py", line 29, in <module>
    from .DualCoverageSet import DualCoverageSet
  File "/scratch/software/lib/python3.6/site-packages/rgt/THOR/DualCoverageSet.py", line 27, in <module>
    from normalize import get_normalization_factor
ModuleNotFoundError: No module named 'normalize'

Would appreciate any help on what might be going on. Also just to clarify, I had installed RGT using a combination of conda and pip so dont know if that has something to do with this.

Thanks

**Comment by fabio-t** [comment]
Hi, we don't currently support Python 3.6, although we will by the end of this year.

Either reinstall everything with python 2.7, or wait a few months. Sorry :)
