### ISSUE TITLE
AttributeError: GenomicSignal instance has no attribute 'bam'

### ISSUE THREAD

**Issue by YichaoOU** [CostaLab/reg-gen#127]
Getting this error. I was able to run this without error on some small datasets. But when I got excited and trying to use it on a project that I'm current working on. I got this error:

> Traceback (most recent call last):
  File "/home/yli11/.conda/envs/costa_RGT_footprint/bin/rgt-hint", line 11, in <module>
    load_entry_point('RGT==0.12.1', 'console_scripts', 'rgt-hint')()
  File "/research/rgs01/home/clusterHome/yli11/.conda/envs/costa_RGT_footprint/lib/python2.7/site-packages/rgt/HINT/Main.py", line 90, in main
    args.func(args)
  File "/research/rgs01/home/clusterHome/yli11/.conda/envs/costa_RGT_footprint/lib/python2.7/site-packages/rgt/HINT/Tracks.py", line 59, in tracks_run
    get_bc_tracks(args)
  File "/research/rgs01/home/clusterHome/yli11/.conda/envs/costa_RGT_footprint/lib/python2.7/site-packages/rgt/HINT/Tracks.py", line 190, in get_bc_tracks
    min_length=None, max_length=None, strand=False)
  File "/research/rgs01/home/clusterHome/yli11/.conda/envs/costa_RGT_footprint/lib/python2.7/site-packages/rgt/HINT/signalProcessing.py", line 920, in get_bc_signal_by_fragment_length
    for read in self.bam.fetch(ref, p1, p2):
AttributeError: GenomicSignal instance has no attribute 'bam'

**Comment by YichaoOU** [comment]
`rgt-hint tracks --bc --bigWig xx.bam xxx.narrowPeak`

**Comment by ceegeeCode** [comment]
Hi,
I wonder what the solution was here. I'm getting the same type of error running a command like this:

rgt-hint tracks --bc --bigWig --organism=hg19 xx.bam xxx.narrowPeak.sorted --output-location=$HINTOUT --output-prefix=track_$PEAKCALLER.REF_chr$nr
Traceback (most recent call last):
  File "/home/cbmr/tkj375/.local/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/Tracks.py", line 59, in tracks_run
    get_bc_tracks(args)
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/Tracks.py", line 190, in get_bc_tracks
    min_length=None, max_length=None, strand=False)
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/signalProcessing.py", line 911, in get_bc_signal_by_fragment_length
    for read in self.bam.fetch(ref, p1, p2):
AttributeError: 'GenomicSignal' object has no attribute 'bam'

This only occurs for some of my data, which are grouped by chromosome (human, hg19); I don't get the error for eg chromosome 3,5,12 but for 1,6,7.

Kind regards, Christian G

**Comment by ceegeeCode** [comment]
Hi,
I wonder what the solution was here. I'm getting the same type of error running a command like this:

rgt-hint tracks --bc --bigWig --organism=hg19 xx.bam xxx.narrowPeak.sorted --output-location=$HINTOUT --output-prefix=track_$PEAKCALLER.REF_chr$nr
Traceback (most recent call last):
  File "/home/cbmr/tkj375/.local/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/Tracks.py", line 59, in tracks_run
    get_bc_tracks(args)
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/Tracks.py", line 190, in get_bc_tracks
    min_length=None, max_length=None, strand=False)
  File "/home/cbmr/tkj375/.local/lib/python3.6/site-packages/rgt/HINT/signalProcessing.py", line 911, in get_bc_signal_by_fragment_length
    for read in self.bam.fetch(ref, p1, p2):
AttributeError: 'GenomicSignal' object has no attribute 'bam'

This only occurs for some of my data, which are grouped by chromosome (human, hg19); I don't get the error for eg chromosome 3,5,12 but for 1,6,7.

Kind regards, Christian G
