### ISSUE TITLE
Installing development version of rgt get's utf error

### ISSUE THREAD

**Issue by JungWoongJae** [CostaLab/reg-gen#141]
Hi, I'm trying to install development version of rgt to not get error while running _rgt-hint differential_ anaylsis below
```
ERROR:root:get bias corrected signal failed
Traceback (most recent call last):
  File "/das1/.local/lib/python3.6/site-packages/rgt/HINT/DifferentialAnalysis.py", line 170, in diff_analysis_run
    signals[i] = np.array(res)
TypeError: float() argument must be a string or a number, not 'MapResult'
```

So I thought to not get such error, I should install development version of rgt.

But when installing development version, error occurs for utf something like below.
```
Traceback (most recent call last):
  File "setup.py", line 448, in <module>
    platforms=supported_platforms)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 732, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 606, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 25: invalid start byte
```

How can I fix this and install rgt properly?
Thank you

**Comment by fabio-t** [comment]
You should use python 2.7 and install the official version using pip, eg `pip install --user rgt`. The version supporting Python 3 is almost out, maybe this week.
