### ISSUE TITLE
genome_hg19.fa file not found

### ISSUE THREAD

**Issue by MzwaneleN** [CostaLab/reg-gen#153]
I am trying to go through the HINT ATAC tutorial and the got the following error about the hg19 ref genome fasta file:

Traceback (most recent call last):
  File "/home/mngubo/.local/bin/rgt-hint", line 11, in <module>
    sys.exit(main())
  File "/home/mngubo/.local/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/mngubo/.local/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/home/mngubo/.local/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 252, in atac_seq
    fasta = Fastafile(genome_data.get_genome())
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 155, in pysam.libcfaidx.FastaFile._open
IOError: file `/home/mngubo/rgtdata/hg19/genome_hg19.fa` not found

Could it be that somehow the package is missing ref genome hg19?

**Comment by fabio-t** [comment]
Hi, you need to run the following script inside the rgtdata directory:

python setupGenomicData --hg19
We don't ship the genome data with the package - it would be too large. You
can read more instructions here:

https://www.regulatory-genomics.org/rgt/rgt-data-folder/
