### ISSUE TITLE
KeyError: '\x00'

### ISSUE THREAD

**Issue by zhypan** [CostaLab/reg-gen#159]
Hi After I install the RGT and run the example. I got such an error. How can I fix it? Thanks

~/.local/bin/rgt-hint footprinting --atac-seq ATAC.bam ATACPeaks.bed
Traceback (most recent call last):
  File "/home/zhypan/.local/bin/rgt-hint", line 10, in <module>
    sys.exit(main())
  File "/home/zhypan/.local/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/zhypan/.local/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/home/zhypan/.local/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 148, in atac_seq
    hmm = joblib.load(hmm_file)
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '\x00'

**Comment by lzj1769** [comment]
hi,

RGT only supports python3. 
Please upgrade to python3 and try it again.

best,
Li

**Comment by zhypan** [comment]
Thanks, it works after I update to python3
