### ISSUE TITLE
No option 'gene_regions' in section: 'susScr11'

### ISSUE THREAD

**Issue by zhypan** [CostaLab/reg-gen#160]
Hi, I try to work on pig,  so I edit the data.config.user file. but it keeps have an error No option 'gene_regions' in section: 'susScr11'. Can I know how to fix it?
 
edit data.config.user  
[susScr11]
genome: /group/zhougrp/zhangyuan/genome/pig/susScr11.fa
chromosome_sizes: /group/zhougrp/FAANG/Pig/ChromHMM/Chromosome_Lengths.txt
annotation: /group/zhougrp/zhangyuan/genome/pig/susScr11_Ensembl100_modify_1.gtf
gene_regions: /group/zhougrp/zhangyuan/genome/pig/part_change_esemb100/Gene_esemble100_colin.bed

my script
~/.local/bin/rgt-hint footprinting --atac-seq --paired-end --organism susScr11 --output-prefix Jejunum_P348_Footprints --output-location /group/zhougrp/zhangyuan/Pig_all/Aligned_Reads/Footprint/ /group/zhougrp/zhangyuan/Pig_eight/Aligned_Reads/ATAC_Adipose_P348.bam /group/zhougrp/zhangyuan/Pig_eight/Peak_Calls/ATAC_Adipose_P348_Peaks.bed

error
Traceback (most recent call last):
  File "/home/zhypan/.conda/envs/atac/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/home/zhypan/.conda/envs/atac/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/zhypan/.conda/envs/atac/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'gene_regions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhypan/.local/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/home/zhypan/.local/lib/python3.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/zhypan/.local/lib/python3.7/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/home/zhypan/.local/lib/python3.7/site-packages/rgt/HINT/Footprinting.py", line 134, in atac_seq
    genome_data = GenomeData(args.organism)
  File "/home/zhypan/.local/lib/python3.7/site-packages/rgt/Util.py", line 93, in __init__
    self.gene_regions = os.path.join(self.data_dir, self.config.get(organism, 'gene_regions'))
  File "/home/zhypan/.conda/envs/atac/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gene_regions' in section: 'susScr11'

**Comment by fabio-t** [comment]
Hi,

Have you updated to the latest release? What does `rgt-hint --version` say?

**Comment by fabio-t** [comment]
If you don't have version `0.13.1` and you won't/can't upgrade, simply change the `gene_regions` key to `genes_Gencode` inside your data.config.user:

```
genes_Gencode: /group/zhougrp/zhangyuan/genome/pig/part_change_esemb100/Gene_esemble100_colin.bed
```
