### ISSUE TITLE
error when generating wig files 

### ISSUE THREAD

**Issue by rm1238** [CostaLab/reg-gen#171]
Hello,

I successfully performed footprinting but am getting an error when trying to generate the bw files for visualization.
The problem seems to be the random sequences within the hg19 assembly, which appear to be contained in the h9g19 genome after configuring it after rgt installation.

rgt-hint tracks --bc --bigWig --organism=hg19 EV_ATAC_blacklisted.merge.bam ESCAPE_ATAC_IN_K4me1_K27ac.bed --output-prefix=./HINT/ATAC_EV_IN_K4me1_K27ac_HINT
Traceback (most recent call last):
  File "/Users/ivancorea/.local/bin/rgt-hint", line 10, in <module>
    sys.exit(main())
  File "/Users/ivancorea/.local/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/Users/ivancorea/.local/lib/python2.7/site-packages/rgt/HINT/Tracks.py", line 59, in tracks_run
    get_bc_tracks(args)
  File "/Users/ivancorea/.local/lib/python2.7/site-packages/rgt/HINT/Tracks.py", line 190, in get_bc_tracks
    min_length=None, max_length=None, strand=False)
  File "/Users/ivancorea/.local/lib/python2.7/site-packages/rgt/HINT/signalProcessing.py", line 936, in get_bc_signal_by_fragment_length
    currStr = str(fasta.fetch(ref, p1_wk, p2_wk - 1)).upper()
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
**KeyError: "sequence 'chr17_gl000205_random' not present"**

Any advice as to how to work around this would be greatly appreciated.

Thanks,

Ricardo

**Comment by lzj1769** [comment]
Hi,

It looks like rgt-hint can not find chr17_gl000205_random in your reference genome.
To solve it, you can remove the peaks from these unusual chromosomes, for example, only keep chr1-22 and chrX.

best,
Li
