### ISSUE TITLE
KeyError: "sequence 'chr1_GL456211_random' not present"

### ISSUE THREAD

**Issue by VEG-CC** [CostaLab/reg-gen#190]
Hi,
I would like to run the HINT-ATAC footprint for my ATAC-seq data, and it stops with the following error:

```shell
$ rgt-hint footprinting --atac-seq --organism=mm10 --output-location=./WT_DP --output-prefix=wtdp ../bam/WT_DP.bam ../peaks/narrowPeak/WT_DP.narrowPeak

Traceback (most recent call last):
  File "/Users/dd/.local/bin/rgt-hint", line 33, in <module>
    sys.exit(load_entry_point('RGT==0.13.2', 'console_scripts', 'rgt-hint')())
  File "/Users/dd/.local/lib/python3.9/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/Users/dd/.local/lib/python3.9/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/Users/dd/.local/lib/python3.9/site-packages/rgt/HINT/Footprinting.py", line 351, in atac_seq
    reads_file.get_signal_atac(region.chrom, region.initial, region.final, downstream_ext,
  File "/Users/dd/.local/lib/python3.9/site-packages/rgt/HINT/signalProcessing.py", line 153, in get_signal_atac
    bc_signal_forward, bc_signal_reverse = self.bias_correction_atac(bias_table, genome_file_name,
  File "/Users/dd/.local/lib/python3.9/site-packages/rgt/HINT/signalProcessing.py", line 386, in bias_correction_atac
    currStr = str(fastaFile.fetch(chrName, p1_wk, p2_wk - 1)).upper()
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence 'chr1_GL456211_random' not present"
```

I have tried to run the tutorial data in the [HINT webs](http://www.regulatory-genomics.org/hint/tutorial/), and it worked good in my mac, so I think there are something wrong for my data. I wonder how to fix it.

Thank!

**Comment by lzj1769** [comment]
Hi @VEG-CC ,

This means RGT-HINT cannot find the reference  sequence for this DNA regions: chr1_GL456211_random

To fix it, you can remove all peaks from this chromosome, here is what I usually do for this:
`sed -i '/random\|chrUn\|chrM/d' peaks.narrowPeak`

best,
Li

**Comment by lzj1769** [comment]
closed if no further comments.
