### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by anacatalan** [CostaLab/reg-gen#196]
Dear HINT developer,
I've installed HINT on an hpc and I'm getting this error:

Used command: $pathH/rgt-hint footprinting --atac-seq $bed $bam

```
Traceback (most recent call last):
  File "/dss/dsshome1/lxc07/lu32gib/.local/bin//rgt-hint", line 5, in <module>
    from rgt.HINT.Main import main
  File "/dss/dsshome1/lxc07/lu32gib/.local/lib/python3.7/site-packages/rgt/HINT/Main.py", line 14, in <module>
    from rgt.HINT.Training import training_args, training_run
  File "/dss/dsshome1/lxc07/lu32gib/.local/lib/python3.7/site-packages/rgt/HINT/Training.py", line 11, in <module>
    from rgt.HINT.hmm import HMM, SemiSupervisedGaussianHMM
  File "/dss/dsshome1/lxc07/lu32gib/.local/lib/python3.7/site-packages/rgt/HINT/hmm.py", line 3, in <module>
    from hmmlearn.hmm import GaussianHMM
  File "/dss/dsshome1/lxc07/lu32gib/.local/lib/python3.7/site-packages/hmmlearn/hmm.py", line 20, in <module>
    from .base import _BaseHMM
  File "/dss/dsshome1/lxc07/lu32gib/.local/lib/python3.7/site-packages/hmmlearn/base.py", line 13, in <module>
    from . import _hmmc
ImportError: /dss/dsshome1/lxc07/lu32gib/.local/lib/python3.7/site-packages/hmmlearn/_hmmc.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strlen

Do you know how I can handle this error?

Cheers,

Ana

**Comment by lzj1769** [comment]
Hi Ana,

This problem was caused by the hmm-learn library which didn't work out with the inter compliers.

To solve it, you can try to set the compiler to GCC by `export CC=gcc` and re-install hmm-learn.

best,
Li

**Comment by lzj1769** [comment]
Closed if no further comments, feel free to re-open it if there are any questions.
