### ISSUE TITLE
rgt-motifanalysis install error

### ISSUE THREAD

**Issue by dahun73** [CostaLab/reg-gen#198]
Hello, 

I have trouble of installation of rgt-motifanalysis

```
Traceback (most recent call last):
  File "/home/nepi/.local/lib/python3.8/site-packages/MOODS/tools.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/nepi/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/nepi/.local/lib/python3.8/site-packages/MOODS/_tools.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nepi/.local/bin/rgt-motifanalysis", line 5, in <module>
    from rgt.motifanalysis.Main import main
  File "/home/nepi/.local/lib/python3.8/site-packages/rgt/motifanalysis/Main.py", line 16, in <module>
    from . import Match
  File "/home/nepi/.local/lib/python3.8/site-packages/rgt/motifanalysis/Match.py", line 21, in <module>
    from ..MotifSet import MotifSet
  File "/home/nepi/.local/lib/python3.8/site-packages/rgt/MotifSet.py", line 17, in <module>
    from rgt.motifanalysis.Motif import Motif
  File "/home/nepi/.local/lib/python3.8/site-packages/rgt/motifanalysis/Motif.py", line 13, in <module>
    from MOODS import tools, parsers
  File "/home/nepi/.local/lib/python3.8/site-packages/MOODS/tools.py", line 17, in <module>
    _tools = swig_import_helper()
  File "/home/nepi/.local/lib/python3.8/site-packages/MOODS/tools.py", line 16, in swig_import_helper
    return importlib.import_module('_tools')
  File "/home/nepi/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_tools'
```

'rgt-hint' is running well. However, only rgt-motifanalysis is not working now.
Version of python is 3.8.8.

Thank you in advance :)

**Comment by fabio-t** [comment]
Hi, can you share how you installed RGT?

**Comment by dahun73** [comment]
> Seems to be an issue with GCC+conda [cython/cython#4218](https://github.com/cython/cython/issues/4218) I'm not totally sure though, I don't have conda (and we don't directly support that platform for RGT). But it's worth a try to downgrade to gcc10 if you are using gcc11 within conda, remove the MOODS package and reinstall it again.
> 
> MOODS is the main dependency of rgt-motifanalsysis, we don't manage that either. But it has its own github repository: https://github.com/jhkorhonen/MOODS

Thank you for reply!

I tried to downgrade gcc version from 11 to 10. It is hard to do this. I downloaded gcc10 version and remove gcc11. However, gcc10 is not working now.

![image](https://user-images.githubusercontent.com/52641420/149069376-cc4323a9-4dd9-4e92-b03d-32ca09daca48.png)


Should I try to make conda environment in order to install RGT?
Anyway, I'm trying to downgrade gcc version again!!

If I succeed, I will let you know right away.

Thanks :)

**Comment by lzj1769** [comment]
Hi,

Should I try to make conda environment in order to install RGT?


I think this is the easiest way to install RGT and I always use conda to
set a specific environment for RGT.
After setting up and activating your envrioment, you can install it by:
pip install RGT

Best,
Li


*______________________________*
Zhijian Li
Institute for Computational Genomics
RWTH Aachen University
Pauwelsstrasse 19
52074 Aachen, Germany

**Comment by hyjforesight** [comment]
```linux
# install gcc and dependencies MOODS-python
$ sudo apt update
$ sudo apt install build-essential
$ gcc --version
$ pip3 install --user MOODS-python

$ pip3 install --user cython numpy scipy
$ pip3 install --user RGT
```
this works for me

**Comment by lzj1769** [comment]
Closed if no further comments.
