### ISSUE TITLE
Issue Promoter Test

### ISSUE THREAD

**Issue by Galadrast85** [CostaLab/reg-gen#201]
Hi I have problems with the promoter_test that gives me this error

*************** Promoter Test ****************
*** Input RNA sequence: /home/bioinfo/rgtdata/Loc100420879/Loc100420879.fasta
*** Output directory: Loc100420879/promoter_test/Loc100420879
Step 1: Calculate the triplex forming sites on RNA and DNA.
	Dump to file: tdf.dump.hg19.total_genes
	Running time: 0:03:24
Step 2: Calculate the frequency of DNA binding sites within the promoters.
	Counting frequency of promoters on DBD...
		158	Binding target promoters
		57	Binding non-target promoters
	Counting frequency of binding sites on DBD...
		158	Binding sites on de promoters
Traceback (most recent call last):
  File "/home/bioinfo/.local/bin/rgt-TDF", line 8, in <module>
    sys.exit(main())
  File "/home/bioinfo/.local/lib/python3.8/site-packages/rgt/tdf/Main.py", line 354, in main
    stat.count_frequency_promoters(target_regions=tdf_input.dna.target_regions,
  File "/home/bioinfo/.local/lib/python3.8/site-packages/rgt/tdf/Statistics.py", line 129, in count_frequency_promoters
    self.promoter["nde"]["dbs"][p.toString()] = counts[i]
**IndexError: list index out of range**

Where am I wrong? Thank you in advance

**Comment by hyjforesight** [comment]
Hello @Galadrast85 
May I know how you ran through the rgt-motifanalysis matching?
I met `KeyError: "sequence 'chr22' not present"` when running the tutorial. Thanks!
```linux
rgt-motifanalysis matching --organism hg19 --fpr 0.05 --input-files ~/RGT_MotifAnalysis_FullSiteTest/input/regions_K562.bed ~/RGT_MotifAnalysis_FullSiteTest/input/background.bed --output-location ~/RGT_MotifAnalysis_FullSiteTest/motif_matching/
```
