### ISSUE TITLE
RGT_Differential_Error

### ISSUE THREAD

**Issue by rm1238** [CostaLab/reg-gen#246]
Hello,

Sorry to bother you again. I was trying to run a differential analysis and the error below popped back:

**### **Traceback (most recent call last):

  File "/Users/ivancorea/miniconda3/bin/rgt-hint", line 33, in <module>

    sys.exit(load_entry_point('RGT==1.0.0', 'console_scripts', 'rgt-hint')())

  File "/Users/ivancorea/miniconda3/lib/python3.8/site-packages/rgt/HINT/Main.py", line 95, in main

    args.func(args)

  File "/Users/ivancorea/miniconda3/lib/python3.8/site-packages/rgt/HINT/DifferentialAnalysis.py", line 183, in diff_analysis_run

    motif_pwm.append(get_pwm(fasta, mpbs_regions, args.window_size))

  File "/Users/ivancorea/miniconda3/lib/python3.8/site-packages/rgt/HINT/DifferentialAnalysis.py", line 476, in get_pwm

    dna_seq_rev = AuxiliaryFunctions.revcomp(str(fasta.fetch(region.chrom,

  File "/Users/ivancorea/miniconda3/lib/python3.8/site-packages/rgt/Util.py", line 1161, in revcomp

    return "".join([revDict[e] for e in s[::-1]])

  File "/Users/ivancorea/miniconda3/lib/python3.8/site-packages/rgt/Util.py", line 1161, in <listcomp>

    return "".join([revDict[e] for e in s[::-1]])

KeyError: '7'****

Any suggestions on how to fix it would be greatly appreciated.

Thank you,

Ricardo

**Comment by rm1238** [comment]
Hi there,

The chromosome name seems normal to me. See screenshot attached.
Also see screenshot of error for clarity.
I aligned my data to GRCh38.d1.vd1. I have worked with this assembly in the past with RGT-HINT and did not have an issue.

Any suggestions are greatly appreciated.

Thanks,

Ricardo
<img width="811" alt="Screenshot 2023-03-27 at 10 17 12" src="https://user-images.githubusercontent.com/49791648/227967203-1e58be62-d35d-4048-9e51-f4364b8be911.png">


<img width="569" alt="Screenshot 2023-03-27 at 10 16 15" src="https://user-images.githubusercontent.com/49791648/227966617-8e4c58e1-6a1e-41cf-b3e1-b4bbd3607660.png">

**Comment by rm1238** [comment]
Hi Zhijian,

Just looping back to ask if you had a suggestion as to how to correct this error. Thank you again,

Ricardo

**Comment by lzj1769** [comment]
Hi Ricardo,

Sorry for the late reply.

To figure it out, would it be possible for you to share some data that can reproduce this error?

I will then dive deeper to see what is going wrong.

Best,
Zhijian

**Comment by rm1238** [comment]
Hi Zhijian,

How can I share data with you? I have shared some files in the past but not sure posting a live on Github is a good idea. Can you email me at rm1238@rutgers.edu to set up the data share?

Ricardo
