### ISSUE TITLE
Issues with rgt-motifanalysis

### ISSUE THREAD

**Issue by RaghadShu** [CostaLab/reg-gen#280]
Hi, 
When I run this command `rgt-motifanalysis` I get this error:
`Traceback (most recent call last):
  File "/home/rshuwaikan/anaconda3/envs/rgt/bin/rgt-motifanalysis", line 5, in <module>
    from rgt.motifanalysis.Main import main
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/motifanalysis/Main.py", line 17, in <module>
    from . import Enrichment
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/motifanalysis/Enrichment.py", line 24, in <module>
    from fisher import pvalue
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/fisher/__init__.py", line 3, in <module>
    from .cfisher import *
  File "src/cfisher.pyx", line 1, in init fisher.cfisher
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

I am running rgt using conda :) 
Any tips on how to fix this?
Best,
Raghad

**Comment by RaghadShu** [comment]
This got fixed by downgrading numpy, something like this `pip3 install numpy==1.26.4` worked fine for me
Closing for now
