### ISSUE TITLE
rgt-TDF problem

### ISSUE THREAD

**Issue by Charbelfeg** [CostaLab/reg-gen#284]
Hello,

I am trying to install TDF, however i am facing the following issue after running rgt-TDF promotertest

rgt-TDF promotertest
Traceback (most recent call last):
  File "/home/charbel/miniconda3/envs/bioinfo/bin/rgt-TDF", line 5, in <module>
    from rgt.tdf.Main import main
  File "/home/charbel/miniconda3/envs/bioinfo/lib/python3.6/site-packages/rgt/tdf/Main.py", line 12, in <module>
    matplotlib.use('Agg', warn=False)
TypeError: use() got an unexpected keyword argument 'warn'
(bioinfo)

Any ideas how to resolve this please?

Thanks a lot

**Comment by chaochungkuo** [comment]
Hi,

TDF wasn't updated for some years. It is very likely that your matplotlib
version is too new. Please try to downgrade your matplotlib.

*Joseph Chao-Chung Kuo*

Dr. Chao-Chung Kuo
Genomics Facility, IZKF Aachen, RWTH Aachen University
Phone: +49 241 80 35296
e-mail: ***@***.***
Web: genomics.rwth-aachen.de



Am Do., 26. Sept. 2024 um 14:26 Uhr schrieb Charbelfeg <
***@***.***>:
