### ISSUE TITLE
rgt-hint differential Error

### ISSUE THREAD

**Issue by nihenniuwa** [CostaLab/reg-gen#285]
When I run the rgt-hintdifferential, there are the following errors, how to solve them?

signal generation is done!

generating line plot for each motif...

multiprocessing.pool.RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/home/rui/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker

    result = (True, func(*args, **kwds))

  File "/home/rui/miniconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar

    return list(map(*args))

  File "/home/rui/miniconda3/lib/python3.9/site-packages/rgt/HINT/DifferentialAnalysis.py", line 506, in output_line_plot

    with open(output_filename, "w") as f:

OSError: [Errno 22] Invalid argument: './DiffFootprinting/Lineplots/MA1128.1.FOSL1::JUN.txt'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/rui/miniconda3/bin/rgt-hint", line 8, in <module>

    sys.exit(main())

  File "/home/rui/miniconda3/lib/python3.9/site-packages/rgt/HINT/Main.py", line 95, in main

    args.func(args)

  File "/home/rui/miniconda3/lib/python3.9/site-packages/rgt/HINT/DifferentialAnalysis.py", line 258, in diff_analysis_run

    pool.map(output_line_plot, arguments_list)

  File "/home/rui/miniconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map

    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "/home/rui/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get

    raise self._value

OSError: [Errno 22] Invalid argument: './DiffFootprinting/Lineplots/MA1128.1.FOSL1::JUN.txt'
I returned the same error when I ran the sample file.

**Comment by songw01** [comment]
I get the same error. Is there a solution to this?

**Comment by nihenniuwa** [comment]
> I get the same error. Is there a solution to this?

This problem is because ":" is a special character and cannot be used for file names. I tried to handle file names in DifferentialAnalysis.py script by replacing "::" with other legal characters, such as "_". Find the part of the script responsible for generating the file name (the output_line_plot function) and replace the illegal characters before creating the file.
def output_line_plot(arguments):
    (mpbs_name, mpbs_num, signals, conditions, pwm, output_location, window_size, colors) = arguments
    
    # replace characters that might make the file name invalid
    safe_mpbs_name = mpbs_name.replace("::", "_").replace("(", "_").replace(")", "")

    # output signal
    output_filename = os.path.join(output_location, "{}.txt".format(safe_mpbs_name))
    with open(output_filename, "w") as f:
        f.write("\t".join(conditions) + "\n")
        for i in range(window_size):
            res = []
            for j, condition in enumerate(conditions):
                res.append(signals[j][i])

            f.write("\t".join(map(str, res)) + "\n")
This is the modified part of the code, may need to be modified, for reference only.

**Comment by songw01** [comment]
I am new to python, and wonder if this is simply matter of changing the code in the file? Or do you have the patched source file?

**Comment by nihenniuwa** [comment]
> 我是 Python 新手，不知道这是否只是更改文件中的代码的问题？或者您有修补过的源文件吗？

[DifferentialAnalysis.zip](https://github.com/user-attachments/files/17968209/DifferentialAnalysis.zip)
This is the file I changed. The change to the script only involves generating the file name, and the modification does not involve any calculation logic, nor does it change the semantics of mpbs_name, so I think it will not affect the operation of the code and the accuracy of the result. There was no anomaly when I used it.
