### ISSUE TITLE
THOR- Issue in regenerating report

### ISSUE THREAD

**Issue by jovesus** [CostaLab/reg-gen#32]
Below is the error message I got when I set `--report` in the command.

I will also check it later.
```
Call DPs on whole genome.
Computing read extension sizes for ChIP-seq profiles
Compute GC-content
Compute factors
Normalize input of Signal 0, Rep 0 with factor 0.767
Normalize input of Signal 0, Rep 1 with factor 0.767
Normalize input of Signal 1, Rep 0 with factor 0.769
Normalize input of Signal 1, Rep 1 with factor 0.769
Use global TMM approach 
Traceback (most recent call last):
  File "/work/ck687463/bin/rgt-THOR", line 11, in <module>
    load_entry_point('RGT==0.10.0', 'console_scripts', 'rgt-THOR')()
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/RGT-0.10.0-py2.7.egg/rgt/THOR/THOR.py", line 157, in main
    chrom_sizes, dims, inputs, tracker)
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/RGT-0.10.0-py2.7.egg/rgt/THOR/THOR.py", line 81, in train_HMM
    report=options.report, poisson=options.poisson)
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/RGT-0.10.0-py2.7.egg/rgt/THOR/dpc_help.py", line 197, in _fit_mean_var_distr
    _plot_func(plot_data, outputdir)
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/RGT-0.10.0-py2.7.egg/rgt/THOR/dpc_help.py", line 108, in _plot_func
    maxs.append(max(tmp[tmp < np.percentile(tmp, 90)]))
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4116, in percentile
    interpolation=interpolation)
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3858, in _ureduce
    r = func(a, **kwargs)
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4233, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 134, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/rwthfs/rz/cluster/work/ck687463/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

**Comment by KFDing** [comment]
tomorrow goes to the office, and check on it.

Am 22.08.2017 10:40 schrieb "Joseph Kuo" <notifications@github.com>:

**Comment by fabioticconi** [comment]
@jovesus were you able to re-run the experiment that caused this?

**Comment by npavlovikj** [comment]
Hi,

I just downloaded "RGT-0.11.4", and I am encountering the same error when running "rgt-THOR" with "--report". Is there some workaround for this?

Thank you,
Natasha

**Comment by havardtl** [comment]
Hi, 

It seems like I have also encountered the same error. It happens for all 5 of my antibodies. I also recently downloaded "RGT-0.11.4". Here is the error report for one of them: 

```
rgt-THOR thor_configs/180206_CREplus-H3K9me2_S10.config --report --output-dir thor_diffpeaks/180206_CREplus-H3K9me2_S10 --name 180206_CREplus-H3K9me2_S10
Warning: Do not compute GC-content, as there is no genome file
Call DPs on whole genome.
Computing read extension sizes for ChIP-seq profiles
/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Compute factors
Normalize input of Signal 0, Rep 0 with factor 0.535
Normalize input of Signal 1, Rep 0 with factor 0.512
Use global TMM approach
Traceback (most recent call last):
  File "/usr/local/bin/rgt-THOR", line 11, in <module>
    load_entry_point('RGT==0.10.2', 'console_scripts', 'rgt-THOR')()
  File "build/bdist.linux-x86_64/egg/rgt/THOR/THOR.py", line 157, in main
  File "build/bdist.linux-x86_64/egg/rgt/THOR/THOR.py", line 81, in train_HMM
  File "build/bdist.linux-x86_64/egg/rgt/THOR/dpc_help.py", line 198, in _fit_mean_var_distr
  File "build/bdist.linux-x86_64/egg/rgt/THOR/dpc_help.py", line 109, in _plot_func
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 4291, in percentile
    interpolation=interpolation)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 4033, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 4405, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 159, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

```

Content of thor_configs/180206_CREplus-H3K9me2_S10.config: 
```
#rep1
bam_sorted/180206_CREplus-H3K9me2_S10.bam
#rep2
bam_sorted/180206_CREminus-H3K9me2_S4.bam
#chrom_sizes
mouse_GENCODE_M18_GRCm38/chrom_sizes.txt
#inputs1
bam_sorted/180206_CREplus-INPUT_S12.bam
#inputs2
bam_sorted/180206_CREminus-INPUT_S6.bam

```
```
rgt-THOR --version
0.10.2
```

I will be happy to supply more information if that might help the debugging. 

Regards, 
Håvard

**Comment by laijen000** [comment]
Hi all! I am getting the same IndexError with version 0.13.1 and I ran with the command --report. Has this issue been resolved? Or am I unable to run with --report? Thank you!
