### ISSUE TITLE
THOR DeprecationWarning using example data

### ISSUE THREAD

**Issue by dy7t** [CostaLab/reg-gen#35]
rgt-THOR failed to create output files when running its example data as described at:
http://www.regulatory-genomics.org/thor-2/basic-intrstruction/

See details below:

Installed Python 2.7.13 then:
```
$ pip install cython numpy scipy
$ pip install RGT
$ pip list
biopython (1.70)
cycler (0.10.0)
Cython (0.26.1)
fisher (0.1.4)
functools32 (3.2.3.post2)
hmmlearn (0.2.0)
HTSeq (0.9.1)
matplotlib (2.0.2)
matplotlib-venn (0.11.5)
mpmath (0.19)
natsort (5.1.0)
ngslib (1.1.20)
numpy (1.13.1)
pip (9.0.1)
pyBigWig (0.3.4)
pyparsing (2.2.0)
pysam (0.11.1)
python-dateutil (2.6.1)
pytz (2017.2)
PyVCF (0.6.8)
PyX (0.12.1)
RGT (0.10.0)
scikit-learn (0.19.0)
scipy (0.19.1)
setuptools (36.3.0)
six (1.10.0)
subprocess32 (3.2.7)
wheel (0.29.0)

$ wget http://www.regulatory-genomics.org/wp-content/uploads/2015/07/THOR_example_data.tar.gz
$ tar xzf THOR_example_data.tar.gz 
$ cd THOR_example_data

$ cat THOR.config
#rep1
FL5_H3K27ac.100k.bam
FL8_H3K27ac.100k.bam
#rep2
CC4_H3K27ac.100k.bam
CC5_H3K27ac.100k.bam
#chrom_sizes
hg19.chrom.sizes

$ rgt-THOR ./THOR.config
Warning: Do not compute GC-content, as there is no input file
Warning: Do not compute GC-content, as there is no genome file
Call DPs on whole genome.
Computing read extension sizes for ChIP-seq profiles
Use global TMM approach
Compute HMM's training set
Train HMM
Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/RGT-0.10.0/bin/rgt-THOR", line 11, in <module>
    sys.exit(main())
  File "/group/bioinfo/apps/apps/RGT-0.10.0/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 157, in main
    chrom_sizes, dims, inputs, tracker)
  File "/group/bioinfo/apps/apps/RGT-0.10.0/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 92, in train_HMM
    m.fit([training_set_obs], options.hmm_free_para)
  File "/group/bioinfo/apps/apps/RGT-0.10.0/lib/python2.7/site-packages/rgt/THOR/neg_bin_rep_hmm.py", line 146, in fit
    posteriors = np.exp(gamma.T - logsumexp(gamma, axis=1)).T
  File "/group/bioinfo/apps/apps/RGT-0.10.0/lib/python2.7/site-packages/sklearn/utils/deprecation.py", line 75, in wrapped
    warnings.warn(msg, category=DeprecationWarning)
DeprecationWarning: Function logsumexp is deprecated; sklearn.utils.extmath.logsumexp was deprecated in version 0.19 and will be removed in 0.21. Use scipy.misc.logsumexp instead.
```

**Comment by fabioticconi** [comment]
Thanks for your report. We will look into it soon.

**Comment by dy7t** [comment]
The warning message is coming from the `scikit-learn` package.  One workaround is to use an older version (I tried 0.18.2 instead of the current 0.19.0) and THOR successfully processed its example data.

A better fix is probably to follow the advice in the warning message and replace instances of the `sklearn.utils.extmath.logsumexp` method with `scipy.misc.logsumexp`  Maybe you don't need  `scikit-learn` anymore?  Also, I don't know why the warning message caused `rgt-THOR` to exit.

**Comment by fabioticconi** [comment]
Yep that's correct. It was already being looked at in our THOR-refactoring branch but we will push a fix to develop soon - in time to make it for the upcoming RGT 0.10.11. We'll notify you when it's out.

**Comment by fabioticconi** [comment]
@dy7t the new release 0.10.2 is out - should not crash for warnings anymore, and uses the `scipy.misc.logsumexp function`.
