### ISSUE TITLE
rgt-filterVCF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CostaLab/reg-gen#4]
```
What steps will reproduce the problem?
1. rgt-filterVCF path/to/sample.conf --t-mq 30 --t-dp 40 --list-WT 
path/to/file_wt.config 
2.
3.

What is the expected output? What do you see instead?
-running programm

mbegemann@UK2011001653:~$ rgt-filterVCF 
/home/mbegemann/am_pipeline/reg-gen-read-only/test/sample.conf --t-mq 30 --t-dp 
40 --list-WT /home/mbegemann/am_pipeline/reg-gen-read-only/test/file_wt.config  
Traceback (most recent call last):
  File "/usr/local/bin/rgt-filterVCF", line 9, in <module>
    load_entry_point('RGT==0.0.1', 'console_scripts', 'rgt-filterVCF')()
  File "/usr/local/lib/python2.7/dist-packages/RGT-0.0.1-py2.7.egg/rgt/filterVCF/filterVCF.py", line 151, in main
    sample_data = load_data(vcf_list)
  File "/usr/local/lib/python2.7/dist-packages/RGT-0.0.1-py2.7.egg/rgt/filterVCF/filterVCF.py", line 36, in load_data
    name, path = tmp[0], tmp[1]
IndexError: list index out of range

What version of the product are you using? On what operating system?


Hallo Manuel,
das kommt bei mir raus wenn ich versuche das Programm zu starten. Ich bin mir 
noch nicht sicher ob ich einen synthax-fehler begehe. 
welche Optionen sin zwingend und welche optional? habe ich eine motifs.bed oder 
läd der die automatisch?

Gruß,
Matthias

```

Original issue reported on code.google.com by `M.Begem...@gmail.com` on 1 Dec 2014 at 1:51

**Comment by fabioticconi** [comment]
@ManuelAllh is this a true issue or not relevant anymore?

**Comment by ManuelAllh** [comment]
fixed
