### ISSUE TITLE
HINT import issue

### ISSUE THREAD

**Issue by lzj1769** [CostaLab/reg-gen#62]
Installed RGT with pip in a virtual environment running python 3.6.1

$ rgt-hint footprinting
Traceback (most recent call last): 
  File "/home/x_andtj/.virtualenvs/atac-seq/bin/rgt-hint", line 7, in <module>
    from rgt.HINT.Main import main 
  File "/home/x_andtj/.virtualenvs/atac-seq/lib/python3.6/site-packages/rgt/HINT/Main.py", line 5, in <mo
dule>
    from Training import training_args, training_run
ModuleNotFoundError: No module named 'Training'

**Comment by fabio-t** [comment]
Python 3 is still not supported. Try it with Python 2.

**Comment by lzj1769** [comment]
@fabio-t 

So you mean even if we fixed the import problom, rgt still doesn't work under Python 3.
Is that right?
