### ISSUE TITLE
 rgt-hint footprinting error

### ISSUE THREAD

**Issue by zhuangfjnu** [CostaLab/reg-gen#63]
Hi , when I use rgt-hint footprinting , get some error.

[root@bogon yue]# rgt-hint footprinting --atac-seq --organism=hg38 ./Galaxy396.bam ./Galaxy572.bed --output-prefix=cell
[W::hts_idx_load2] The index file is older than the data file: ./Galaxy396.bai
[W::hts_idx_load2] The index file is older than the data file: ./Galaxy396.bai
divide by zero encountered in log
divide by zero encountered in log
Mean of empty slice.
invalid value encountered in double_scalars
Traceback (most recent call last):
  File "/root/miniconda2/bin/rgt-hint", line 11, in <module>
    load_entry_point('RGT==0.11.2', 'console_scripts', 'rgt-hint')()
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Main.py", line 91, in main
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Footprinting.py", line 105, in footprinting_run
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Footprinting.py", line 332, in atac_seq
  File "build/bdist.linux-x86_64/egg/rgt/HINT/signalProcessing.py", line 168, in get_signal_atac
  File "build/bdist.linux-x86_64/egg/rgt/HINT/signalProcessing.py", line 345, in bias_correction_atac
  File "pysam/libcalignmentfile.pyx", line 793, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 650, in pysam.libchtslib.HTSFile.parse_region
**ValueError: start out of range (-25)**

Any suggestion will be appreciated

**Comment by lzj1769** [comment]
Hi @zhuangfjnu ,

This is the genome border problem that we have been fighting for a long while.
A temporary solution is to remove the begining region of genome from the input file.
We will fix it in our next release.

Thanks,

**Comment by zhuangfjnu** [comment]
Thanks!
