### ISSUE TITLE
TDF fails test in develop

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#65]
```
Traceback (most recent call last):
  File "/home/fabio/.local/bin/rgt-TDF", line 11, in <module>
    sys.exit(main())
  File "/home/fabio/.local/lib/python2.7/site-packages/rgt/tdf/Main.py", line 394, in main
    linelabel="No. DBSs", filename=args.rn + "_lineplot.png")
  File "/home/fabio/.local/lib/python2.7/site-packages/rgt/tdf/Report.py", line 203, in plot_lines
    exons=self.input.rna.regions)
  File "/home/fabio/.local/lib/python2.7/site-packages/rgt/tdf/Report.py", line 324, in lineplot
    f.tight_layout(pad=1.08, h_pad=None, w_pad=None)
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 2275, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 328, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 115, in auto_adjust_subplotpars
    if ax.get_visible()])
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 4182, in get_tightbbox
    bb.append(child._legend_box.get_window_extent(renderer))
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/offsetbox.py", line 266, in get_window_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/offsetbox.py", line 388, in get_extent_offsets
    for c in self.get_visible_children()]
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/offsetbox.py", line 259, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/offsetbox.py", line 478, in get_extent_offsets
    sep, self.mode)
  File "/home/fabio/.local/lib/python2.7/site-packages/matplotlib/offsetbox.py", line 81, in _get_packed_offsets
    sep = (total - sum(w_list)) / (len(w_list) - 1.)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by jovesus** [comment]
fixed in develop branch.
