### ISSUE TITLE
RGT 0.11.3 setup fails (Python 2.7)

### ISSUE THREAD

**Issue by ptrebert** [CostaLab/reg-gen#75]
Hi,
I am trying to install RGT 0.11.3 in a fresh Conda Python 2.7 environment. The `pip install RGT` command fails with the following exception:

```
Exception:
Traceback (most recent call last):
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/pip/wheel.py", line 756, in build
    self.requirement_set.prepare_files(self.finder)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/email/feedparser.py", line 177, in feed
    self._input.push(data)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/email/feedparser.py", line 99, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

For the record, I initially wanted to use Python3, and while the installation seems to succeed, the data setup fails with

```
Traceback (most recent call last):
  File "setupGenomicData.py", line 174, in <module>
    output_genome_file.write(gz_file.read())
TypeError: write() argument must be str, not bytes
```

As I understand, Python3 support is not complete yet, hence I am fine with using Python2, but I can't...

Best,
Peter

**Comment by fabio-t** [comment]
Hi Peter,

We haven't tested it with a conda environment. Would it be possible for you to try with `virtualenv` instead?

Otherwise, I'll need more output before that Exception. RGT has many dependencies, and I don't know which one failed for you here.

[From this link](https://github.com/sphinx-doc/sphinx/issues/3647), it appears that a combination of `conda` and `pip` can produce that error on the `sphinx` package.

Maybe you can try the fix they suggest: `pip install --upgrade sphinx`

**Comment by ptrebert** [comment]
Hi Fabio,
here are the setup progress messages:
```
Collecting RGT
  Using cached https://files.pythonhosted.org/packages/47/ac/c6942c3753c49616f5a4ba654147c6928082d29700172550e358249f6c7c/RGT-0.11.3.tar.gz
Requirement already satisfied: cython in /TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages (from RGT)
Requirement already satisfied: numpy>=1.4.0 in /TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages (from RGT)
Requirement already satisfied: scipy>=1.0.0 in /TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages (from RGT)
Requirement already satisfied: pysam>=0.12.0 in /TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages (from RGT)
Requirement already satisfied: pyBigWig in /TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages (from RGT)
Exception:
Traceback (most recent call last):
[...same as before...]
```

Reading through the info in the issue that you linked, I would now presume that there is something wrong with RGT's requirements - I "fixed" this by running `pip install --upgrade RGT`. It seems to be working now; thanks for pointing in the right direction.

If there are any considerations about making RGT available via (bio)conda, here is a big +1 for that.

Best,
Peter
