### ISSUE TITLE
python setupGenomicData.py --m10 does not work with the new release (rgt-v0.11.4)

### ISSUE THREAD

**Issue by KHBHH** [CostaLab/reg-gen#96]
Hi,

I have downloaded rgt (v0.11.4) from the following website: https://github.com/CostaLab/reg-gen/releases
And then I run the below by typing: 

(env0) bash-4.2$ **python setup.py install --user**
(env0) bash-4.2$**cd rgtdata**

But I am facing an issue when I run the following:
(env0) bash-4.2$ **python setupGenomicData.py --mm10**

Downloading mm10 genome
--2019-01-23 15:43:27--  ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M11/GRCm38.primary_assembly.genome.fa.gz
           => ‘/home/kb246/rgtdata/mm10/GRCm38.primary_assembly.genome.fa.gz’
Resolving ftp.sanger.ac.uk (ftp.sanger.ac.uk)... 193.62.203.115
Connecting to ftp.sanger.ac.uk (ftp.sanger.ac.uk)|193.62.203.115|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/gencode/Gencode_mouse/release_M11 ...
No such directory ‘pub/gencode/Gencode_mouse/release_M11’.

Traceback (most recent call last):
  File "setupGenomicData.py", line 280, in <module>
    gz_file = gzip.open(gz_file_name, 'rb')
  File "/n/app/python/2.7.12/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/n/app/python/2.7.12/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/home/kb246/rgtdata/mm10/GRCm38.primary_assembly.genome.fa.gz'

The issue is when I go to the site 
ftp.sanger.ac.uk > pub > gencode > Read.txt which says: The GENCODE data can now be found at
ftp://ftp.ebi.ac.uk/pub/databases/gencode/

This is the reason why I get the above error I suppose.

Please I would really appreciate if you can tell me how to fix it, or is there later version than rgt-v0.11.4 release? How can I run **python setupGenomicData.py --mm10** without any errors?

Thank you for your help!
Best Regards,
Karni Bedirian

**Comment by KHBHH** [comment]
Thank you Li, it is working now.

Thanks again for the help, appreciated!

Best,
Karni Bedirian
